# Generated by Django 5.0.2 on 2024-05-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(choices=[('Rocket League', 'Rocket League'), ('Minecraft', 'Minecraft'), ('Valorant', 'Valorant')], default='Minecraft', max_length=25)),
                ('teamSize', models.IntegerField(default=0)),
                ('leagueFormat', models.CharField(choices=[('Swiss', 'Swiss'), ('Round Robin', 'Round Robin'), ('Double Round Robin', 'Double Round Robin')], default='Round Robin', max_length=25)),
                ('leagueStructure', models.CharField(choices=[('Open', 'Open'), ('Varsity', 'Varsity'), ('Junior Varsity', 'Junior Varsity'), ('Club', 'Club')], default='Junior Varsity', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=25, unique=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.team')),
            ],
        ),
    ]
