# Generated by Django 5.0.2 on 2024-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=25, unique=True)),
                ('teamSize', models.IntegerField()),
                ('leagueFormat', models.CharField(choices=[('Swiss', 'Swiss'), ('Round Robin', 'Round Robin'), ('Double Round Robin', 'Double Round Robin')], default='Round Robin', max_length=25)),
                ('leagueStructure', models.CharField(choices=[('Open', 'Open'), ('Varsity', 'Varsity'), ('Junior Varsity', 'Junior Varsity'), ('Club', 'Club')], default='Junior Varsity', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=25, unique=True)),
                ('playerCount', models.IntegerField()),
                ('game', models.ManyToManyField(to='tracker.game')),
            ],
        ),
    ]
