# Generated by Django 5.0.2 on 2024-05-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=30)),
                ('teamSize', models.IntegerField(default=0)),
                ('leagueFormat', models.CharField(choices=[('Swiss', 'Swiss'), ('Round Robin', 'Round Robin'), ('Double Round Robin', 'Double Round Robin')], default='Round Robin', max_length=25)),
                ('leagueStructure', models.CharField(choices=[('Open', 'Open'), ('Varsity', 'Varsity'), ('Junior Varsity', 'Junior Varsity'), ('Club', 'Club')], default='Junior Varsity', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponentName', models.CharField(max_length=40)),
                ('opponentAcronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=25, unique=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gameName', models.CharField(default='minecraft', max_length=25)),
                ('homeScore', models.IntegerField(null=True)),
                ('opponentScore', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Final', 'Final'), ('Upcomming', 'Upcomming')], default='Upcomming', max_length=10)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.opponent')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.team')),
            ],
        ),
    ]
