# Generated by Django 5.0.2 on 2024-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameName',
            field=models.CharField(max_length=30),
        ),
    ]
