# Generated by Django 5.0.2 on 2024-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_game_id_game_gameid_alter_game_gamename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teamSize',
        ),
    ]
