# Generated by Django 5.0.2 on 2024-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_match_gamename_match_players_player_kda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='opponent',
        ),
        migrations.AddField(
            model_name='match',
            name='opponentAcronym',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.DeleteModel(
            name='Opponent',
        ),
    ]
