# Generated by Django 5.0.2 on 2024-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_game_teamsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamSize',
            field=models.IntegerField(default=0),
        ),
    ]
