# Generated by Django 5.0.2 on 2024-05-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_match_opponent_match_opponentacronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.team'),
        ),
    ]
