# Generated by Django 5.0.2 on 2024-04-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_game_teamsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='playerCount',
        ),
    ]
