# Generated by Django 5.0.2 on 2024-04-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_team_playercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
