# Generated by Django 5.0.2 on 2024-04-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_team_id_alter_team_teamname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('playerID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('players', models.CharField(max_length=10, verbose_name='Player')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('username', models.CharField(max_length=10, verbose_name='Username')),
                ('kills', models.IntegerField(verbose_name='Kills')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
                ('assists', models.IntegerField(verbose_name='Assists')),
                ('KDA', models.CharField(max_length=11, verbose_name='KDA')),
                ('datePlayed', models.DateField(verbose_name='Date Played')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.players'),
        ),
    ]
