# Generated by Django 5.0.2 on 2024-05-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_players_team_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='players',
            new_name='player',
        ),
    ]
