# Generated by Django 5.0.2 on 2024-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_player_players_remove_team_player_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='null', max_length=20, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
