# Generated by Django 4.2.11 on 2024-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gameName', models.CharField(choices=[('Rocket League', 'Rocket League'), ('Minecraft', 'Minecraft'), ('Valorant', 'Valorant')], default='Minecraft', max_length=25)),
                ('homeScore', models.IntegerField()),
                ('opponentScore', models.IntegerField()),
                ('isLive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('opponentID', models.AutoField(primary_key=True, serialize=False)),
                ('opponentName', models.CharField(max_length=40)),
                ('opponentAcronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='opponentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.opponent'),
        ),
    ]
