# Generated by Django 4.2.11 on 2024-05-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_match_opponent_matchplayers_match_opponentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.team'),
        ),
    ]
