# Generated by Django 4.2.11 on 2024-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_match_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='isLive',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Final', 'Final'), ('Upcomming', 'Upcomming')], default='Upcomming', max_length=10),
        ),
    ]
