# Generated by Django 4.2.11 on 2024-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_match_islive_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchPlayers',
            field=models.ManyToManyField(to='tracker.player'),
        ),
    ]
