# Generated by Django 4.2.11 on 2024-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_match_matchplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchPlayers',
            field=models.ManyToManyField(to='tracker.player'),
        ),
    ]
